name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: mod-version
    attributes:
      label: "Mod Version"
      description: "What version of SSRD are you using?"
      placeholder: "e.g., v1.8"
    validations:
      required: true
  - type: input
    id: other-mod-version
    attributes:
      label: "Other mods being used"
      description: "What other mods are you using, and their versions?"
      placeholder: "e.g., Sodium 0.8.#, Distant Horizons 1.#"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description of the Bug"
      description: "Please provide a clear and concise description of what the bug is, what happens, and how to reproduce it if necesary."
      placeholder: "Describe the issue here..."
    validations:
      required: true
