modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "ssrd_logo.png"

description = '''
This mod re-writes the Sable mod to allow for physics objects (Aeronautics Planes!) to render further out than the normal view distance when using Distant Horizons.
'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sodium"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "distanthorizons"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "sable"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
